name: Metrics
on:
  schedule: 
   - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Coding Habits
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.PAT }}
          user: Fabio-Vicente
          retries: 3
          retries_delay: 300
          retries_output_action: 5
          retries_delay_output_action: 120
          filename: coding-habits.svg
          output_action: none
          template: classic
          base: ""
          config_timezone: America/Bahia
          plugin_habits: yes
          plugin_habits_charts: yes
          plugin_habits_charts_type: classic
          plugin_habits_days: 30
          plugin_habits_from: 1000
          plugin_habits_facts: false
      
      - name: Achievements
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.PAT }}
          user: Fabio-Vicente
          retries: 3
          retries_delay: 300
          retries_output_action: 5
          retries_delay_output_action: 120
          filename: achievements.svg
          output_action: none
          template: classic
          base: ""
          config_timezone: America/Bahia
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: C
      
      - run: |
          sudo mkdir metrics_renders
          sudo mv /metrics_renders/* metrics_renders

      - name: Push metric files
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: metrics
          build_dir: metrics_renders
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}